export const GET_RESTAURANTS = 'GET_RESTAURANTS';
export const FILTER_RESTAURANTS = 'FILTER_RESTAURANTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_LOADING = 'SET_LOADING';
export const RESTAURANT_ERROR = 'RESTAURANT_ERROR';
export const CITY_ERROR = 'CITY_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const GET_MORE = 'GET_MORE';
